### ISSUE TITLE
feat: suggest add pyproject.toml to setup project

### ISSUE THREAD

**Issue by tobiichi3227** [LifeAdventurer/Moonafly#10]
@LifeAdventurer 

The pyproject.toml file is the new standard proposed by PEP-518.
Also it is used by [Poetry](https://github.com/python-poetry/poetry).

It can manage project needs dependency and avoiding dependency version conflict.
The black and isort are integrated with pyproject.toml.
The developer will have the same standard coding style format without any formatter configuration.

**Comment by LifeAdventurer** [comment]
I assigned this issue to you.
