### ISSUE TITLE
feat: add ~/random/vocab/review to terminal mode

### ISSUE THREAD

**Issue by Maverick-K2** [LifeAdventurer/Moonafly#8]

**Comment by LifeAdventurer** [comment]
Thank you for your issue. Could you please provide more details or elaborate further on this feature?

**Comment by Maverick-K2** [comment]
random pick a word in the vocabulary_items list 
count -0.5 every review
also add an option for reviewing the highest counts first

**Comment by LifeAdventurer** [comment]
Thanks

**Comment by Maverick-K2** [comment]
Thanks for adding this feature
