### ISSUE TITLE
Bug: UnicodeDecodeError: 'utf-8' codec can't decode in main.py stderr

### ISSUE THREAD

**Issue by LifeAdventurer** [LifeAdventurer/Moonafly#95]
![image](https://github.com/LifeAdventurer/Moonafly/assets/108756201/dd56e36c-bf83-4da2-b3eb-cba80ed3fabf)

**Comment by LifeAdventurer** [comment]
`0xa0` is the hex representation of `&nbsp` from https://dictionary.cambridge.org/dictionary/english/word
![image](https://github.com/LifeAdventurer/Moonafly/assets/108756201/13c301f7-6031-4aaa-bb31-5dfd24af268a)

**Comment by tobiichi3227** [comment]
This bug doesn't seem to appear in Linux.

**Comment by LifeAdventurer** [comment]
![image](https://github.com/LifeAdventurer/Moonafly/assets/108756201/93d8bf6e-25b7-4dac-afbd-eb4cf1e54a05)
another new problem 
`0x92`

**Comment by LifeAdventurer** [comment]
use
```
cd src
py bot.py
```
when developing
